/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as InspecoesRouteImport } from './routes/inspecoes'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as DevolucoesRouteImport } from './routes/devolucoes'
import { Route as IndexRouteImport } from './routes/index'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecoesRoute = InspecoesRouteImport.update({
  id: '/inspecoes',
  path: '/inspecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucoesRoute = DevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devolucoes': typeof DevolucoesRoute
  '/entregas': typeof EntregasRoute
  '/equipamentos': typeof EquipamentosRoute
  '/inspecoes': typeof InspecoesRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devolucoes': typeof DevolucoesRoute
  '/entregas': typeof EntregasRoute
  '/equipamentos': typeof EquipamentosRoute
  '/inspecoes': typeof InspecoesRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devolucoes': typeof DevolucoesRoute
  '/entregas': typeof EntregasRoute
  '/equipamentos': typeof EquipamentosRoute
  '/inspecoes': typeof InspecoesRoute
  '/menu': typeof MenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devolucoes'
    | '/entregas'
    | '/equipamentos'
    | '/inspecoes'
    | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devolucoes'
    | '/entregas'
    | '/equipamentos'
    | '/inspecoes'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/devolucoes'
    | '/entregas'
    | '/equipamentos'
    | '/inspecoes'
    | '/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevolucoesRoute: typeof DevolucoesRoute
  EntregasRoute: typeof EntregasRoute
  EquipamentosRoute: typeof EquipamentosRoute
  InspecoesRoute: typeof InspecoesRoute
  MenuRoute: typeof MenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecoes': {
      id: '/inspecoes'
      path: '/inspecoes'
      fullPath: '/inspecoes'
      preLoaderRoute: typeof InspecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolucoes': {
      id: '/devolucoes'
      path: '/devolucoes'
      fullPath: '/devolucoes'
      preLoaderRoute: typeof DevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevolucoesRoute: DevolucoesRoute,
  EntregasRoute: EntregasRoute,
  EquipamentosRoute: EquipamentosRoute,
  InspecoesRoute: InspecoesRoute,
  MenuRoute: MenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
